print("Please enter a temperature in Celsius: ")
celsius_input = float(input())
fahrenheit = str((1.8 * celsius_input) + 32)
celsius_output = str(celsius_input)
print(celsius_output + " degrees Celsius is " + fahrenheit + " degrees Fahrenheit")